-- Audit trail and database-level guardrails for ZARO ERP.
-- All writes remain controlled by the existing RPCs.

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);
create index if not exists audit_logs_actor_created_idx
  on public.audit_logs (actor_id, created_at desc);
create index if not exists audit_logs_entity_created_idx
  on public.audit_logs (entity_type, created_at desc);

alter table public.audit_logs enable row level security;
drop policy if exists "owners read audit logs" on public.audit_logs;
create policy "owners read audit logs" on public.audit_logs
  for select to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid()) and p.role = 'owner'
    )
  );

revoke all on public.audit_logs from anon, authenticated;
grant select on public.audit_logs to authenticated;

create or replace function public.zaro_update_section(p_section text, p_payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_allowed boolean := false;
  v_updated integer;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'array' and jsonb_typeof(p_payload) <> 'object' then
    raise exception 'بيانات القسم غير صالحة';
  end if;

  if p_section not in ('orders','products','inventory','shippingCompanies','collections','ads','fixedCosts','cpp') then
    raise exception 'القسم غير مسموح بتعديله';
  end if;

  select role into v_role from public.profiles where id = (select auth.uid());

  if v_role = 'owner' then
    v_allowed := true;
  elsif v_role = 'accountant' and p_section in ('orders','collections') then
    v_allowed := true;
  end if;

  if not v_allowed then
    raise exception 'ليس لديك صلاحية لتعديل هذا القسم';
  end if;

  update public.zaro_state
  set data = jsonb_set(data, array[p_section], p_payload),
      updated_at = now()
  where id = 1;

  get diagnostics v_updated = row_count;
  if v_updated <> 1 then
    raise exception 'تعذر حفظ بيانات النظام';
  end if;

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, details)
  values (
    (select auth.uid()),
    'update_section',
    p_section,
    '1',
    jsonb_build_object('payload_type', jsonb_typeof(p_payload), 'payload_bytes', octet_length(p_payload::text))
  );
end;
$$;

create or replace function public.zaro_set_user_role(p_user_id uuid, p_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caller_role text;
  v_target_role text;
  v_owner_count integer;
  v_updated integer;
begin
  select role into v_caller_role from public.profiles where id = (select auth.uid());
  if v_caller_role is distinct from 'owner' then
    raise exception 'فقط الأونر يقدر يغيّر صلاحيات المستخدمين';
  end if;

  if p_role not in ('pending','owner','accountant','viewer') then
    raise exception 'صلاحية غير معروفة';
  end if;

  select role into v_target_role from public.profiles where id = p_user_id;
  if v_target_role is null then
    raise exception 'المستخدم غير موجود';
  end if;

  if v_target_role = 'owner' and p_role <> 'owner' then
    select count(*) into v_owner_count from public.profiles where role = 'owner';
    if v_owner_count <= 1 then
      raise exception 'لا يمكن إزالة صلاحية آخر أونر في النظام';
    end if;
  end if;

  update public.profiles set role = p_role where id = p_user_id;
  get diagnostics v_updated = row_count;
  if v_updated <> 1 then
    raise exception 'تعذر تحديث صلاحية المستخدم';
  end if;

  insert into public.audit_logs (actor_id, action, entity_type, entity_id, details)
  values (
    (select auth.uid()),
    'change_role',
    'profile',
    p_user_id::text,
    jsonb_build_object('old_role', v_target_role, 'new_role', p_role)
  );
end;
$$;

revoke execute on function public.zaro_update_section(text, jsonb) from public;
revoke execute on function public.zaro_set_user_role(uuid, text) from public;
grant execute on function public.zaro_update_section(text, jsonb) to authenticated;
grant execute on function public.zaro_set_user_role(uuid, text) to authenticated;

create or replace function public.zaro_apply_inventory_movement(
  p_code text,
  p_type text,
  p_qty integer,
  p_reason text,
  p_date date
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_data jsonb;
  v_inventory jsonb;
  v_item jsonb;
  v_index integer;
  v_available integer;
  v_next integer;
  v_movement_id text;
begin
  select role into v_role from public.profiles where id = (select auth.uid());
  if v_role is distinct from 'owner' then
    raise exception 'فقط الأونر يقدر يسجل حركة مخزون';
  end if;
  if p_type not in ('إضافة','خصم') or p_qty is null or p_qty < 1 or coalesce(trim(p_reason), '') = '' or p_date is null then
    raise exception 'بيانات حركة المخزون غير صالحة';
  end if;

  select data into v_data from public.zaro_state where id = 1 for update;
  select (ordinality - 1)::integer, elem into v_index, v_item
  from jsonb_array_elements(coalesce(v_data->'inventory', '[]'::jsonb)) with ordinality
  where elem->>'code' = p_code
  limit 1;

  if v_index is null then
    raise exception 'المنتج غير موجود في المخزون';
  end if;

  v_available := coalesce((v_item->>'available')::integer, 0);
  v_next := v_available + case when p_type = 'إضافة' then p_qty else -p_qty end;
  if v_next < 0 then
    raise exception 'لا يمكن خصم كمية أكبر من الرصيد الحالي';
  end if;

  v_item := jsonb_set(v_item, '{available}', to_jsonb(v_next), true);
  v_inventory := jsonb_set(v_data->'inventory', array[v_index::text], v_item, true);
  v_data := jsonb_set(v_data, '{inventory}', v_inventory, true);
  v_movement_id := md5(clock_timestamp()::text || random()::text);
  v_data := jsonb_set(
    v_data,
    '{inventoryMovements}',
    coalesce(v_data->'inventoryMovements', '[]'::jsonb) || jsonb_build_object(
      'id', v_movement_id,
      'date', p_date,
      'code', p_code,
      'type', p_type,
      'qty', p_qty,
      'reason', trim(p_reason)
    ),
    true
  );

  update public.zaro_state set data = v_data, updated_at = now() where id = 1;
  insert into public.audit_logs (actor_id, action, entity_type, entity_id, details)
  values ((select auth.uid()), 'inventory_movement', 'inventory', p_code, jsonb_build_object('type', p_type, 'qty', p_qty, 'reason', trim(p_reason)));
end;
$$;

revoke execute on function public.zaro_apply_inventory_movement(text, text, integer, text, date) from public;
grant execute on function public.zaro_apply_inventory_movement(text, text, integer, text, date) to authenticated;
